apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "main"
jobs:
  build:
    steps:
      - name: Add labels
        uses: cloudbees-io/label-artifact-version@main
        with:
          component-id: "4a495b74-df03-4aa7-be74-aa2800b1fd14"
          artifact-id: "13d8c5c4-d4f3-49e1-9d55-296d69ab80f4"
          labels: "verified,secure"
          operation: "REPLACE"
