apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Caller workflow

on:
  push:
    branches:
      - main

jobs:
  invoke-reusable:
    uses: ./.cloudbees/workflows/reusable-workflow.yaml
    with:
      run-tests: true
