apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Reusable workflow2

on:
  workflow_call:
    inputs:
      run-tests:
        description: "Run tests"
        required: false
        default: true
        type: boolean

jobs:
  pick:
    steps:
      - name: build-binary - pick
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "build application"
          echo sleep 10


  drop:
    if: inputs.run-tests == true
    steps:
      - name: run tests - drop
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "running tests"
          echo sleep 15