name: PREPROD - GHA Build Artifact Publish Workflow

on:
  push:
    branches:
      - "main"

permissions:
  id-token: write
  contents: read

jobs:
  publish-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Run My Custom Go Action
        uses: cloudbees-io-gha/register-build-artifact@v3
        id: go-action
        with:
          name: "gha-exp6-artifact-2"
          version: "1.0.0"
          url: "docker.io/curlimages/curl:8.13.0"
          digest: "sha256:d43bdb28bae0be0998f3be83199bfb2b81e0a30b034b6d7586ce7e05de34c3fd"
          type: "docker"
          cloudbees-url: "https://api.saas-preprod.beescloud.com"