name: PREPROD - GHA Build Artifact Publish Workflow

on:
  workflow_dispatch:
  
jobs:
  publish-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Run My Custom Go Action
        uses: cloudbees-io-gha/register-build-artifact@v2
        id: go-action
        with:
          name: "gha-exp6-artifact-1"
          version: "1.0.1"
          url: "docker.io/curlimages/curl:8.12.1"
          digest: "sha256:94e9e444bcba979c2ea12e27ae39bee4cd10bc7041a472c4727a558e213744e6"
          type: "docker"
          cloudbees-url: "https://api.saas-preprod.beescloud.com"
          cloudbees-pat: ${{ secrets.CBP_TEST_PAT }}
