name: GH Workflow 3

on: [push]

jobs:
  # These three jobs could easily run in parallel but are set up to run in sequence
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint code
        run: |
          echo "Running linter..."
          sleep 10    # Simulate long linting

  test:
    needs: lint  # Unnecessary dependency; could run in parallel with lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          echo "Running tests..."
          sleep 30   # Slow test suite

      - name: This step is always skipped
        if: github.event_name == 'pull_request'   # (But workflow only runs on `push`)
        run: echo "This never runs."

      - name: Install tool (unnecessary bottleneck)
        run: |
          sudo apt-get update
          sudo apt-get install -y cowsay
          sleep 15   # Simulate slow APT install

      - name: Use installed tool
        run: cowsay "Hello!"

  build:
    needs: test   # Could actually run in parallel, or after lint, but waits for all other jobs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build project
        run: |
          echo "Building..."
          sleep 20   # Simulate a slow build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-build
          path: build/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "Deploying..."
          sleep 10
