name: Manual Caller Workflow

on:
  workflow_dispatch:
     inputs: 
        param1:
          description: 'param1 identifier'
          required: true
        param2:
          description: 'param2 identifier'
          required: true

jobs:
  reusable-1:
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      node-version: "20"
      run-tests: true
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
  reusable-2:
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      node-version: "20"
      run-tests: true
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}