name: Reusable Workflow

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version to use"
        required: false
        default: "18"
        type: string
      run-tests:
        description: "Run tests"
        required: false
        default: true
        type: boolean
    secrets:
      TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install Dependencies
        run: |
          echo "npm install"
          sleep 25

  test:
    if: inputs.run-tests == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          echo "run tests"
          sleep 15

      - name: Upload Test Results
        run: echo "Uploaded results""

  # trigger-r2:
  #   uses: ./.github/workflows/reusable-wf2.yaml
  #   with:
  #     run-tests: true
  #   secrets:
  #     TOKEN: ${{ secrets.GITHUB_TOKEN }}

      