name: Reusable Workflow

on:
  workflow_call:
    inputs:
      run-tests:
        description: "Run tests"
        required: false
        default: true
        type: boolean
    secrets:
      TOKEN:
        required: true

jobs:
  pick-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code - pick
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install Dependencies
        run: |
          echo "npm install"
          sleep 10

  drop-latest:
    if: inputs.run-tests == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Tests - drop
        run: |
          echo "run tests"
          sleep 15

      - name: Upload Test Results
        run: echo "Uploaded results"
